FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y && apt-get install -y build-essential git

RUN git config --global user.email "replel"
RUN git config --global user.name "replel"

COPY templates/common/ /common/
