FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
	emacs \
	git


WORKDIR /build

add . /build/

RUN git clone https://github.com/magnars/dash.el.git /build/dash

RUN $(cd /build/dash && git checkout "732d92eac56023a4fb4a5dc3d9d4e274ebf44bf9")
